import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        < title>Routing in NextJS</title>
        < meta name="description" content="Generated by create next app" />
        < link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className='text-5xl font-bold text-emerald-300'>Routing in NextJS</h1>
    </>
  )
}
